@startuml

interface HTTP

note left of HTTP: Backend

interface Browser

package "Frontend" {
    [Store] -down-> [Component]: refresh state
    [Component] -> [Action]
    [Action] <-> [Axios]
    [Action] -> [Dispatcher]
    [Dispatcher] -> [Store]
}


HTTP -- [Axios]

Browser -- [Component]: click


@enduml
