#!/usr/bin/env bash

CONTAINER_NAME=mongo
MONGODB_USERNAME=mern
MONGODB_PASSWORD=secret
HOST_PORT=27017
MONGODB_PORT=27017

docker run \
  --detach \
  --name $CONTAINER_NAME \
  --publish $HOST_PORT:$MONGODB_PORT \
  --env MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME \
  --env MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD \
  mongo:4.4