version: '3.3'
services:
  mongodb:
    image: 'mongo:5.0'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '127.0.0.1:27017:27017'
#  elastic:
#    image: 'elasticsearch:7.14.2'
#    environment:
#      - discovery.type=single-node
#    ports:
#      - '127.0.01:9200:9200'
#  kibana:
#    image: 'kibana:7.14.2'
#    environment:
#      - 'ELASTICSEARCH_HOSTS=http://elastic:9200'
#    ports:
#      - '127.0.0.1:5601:5601'
#    depends_on:
#      - elastic
  nginx:
    image: 'nginx:1.23'
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - './nginx/conf.d/proxy.conf:/etc/nginx/conf.d/default.conf:ro'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - backend
      - frontend
  backend:
    image: 'node:16.15.1'
    user: 'node'
    working_dir: '/home/node/app'
    environment:
      - 'NODE_ENV=test'
      - 'DB_HOST=mongodb'
      - 'DB_NAME=test'
      - 'DB_USER=root'
      - 'DB_PASSWORD=secret'
    volumes:
      - './backend:/home/node/app'
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - mongodb
    command: 'npm run start:dev'  
  frontend:
    image: 'node:16.15.1'
    user: 'node'
    working_dir: '/home/node/app'
    volumes:
      - './frontend:/home/node/app'
    ports:
      - '127.0.0.1:3001:3001'
    command: 'npm start'  
