# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Frontend Quality Gate

on:
  push:
    branches:
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install
      run: npm install --prefix ./frontend
    - name: Quality Gate
      run: npm run test:quality --prefix ./frontend
